print("========User Information==========")
Customer_Name = input("Enter a name:")
Phone_Number = input("Enter a phone number:")
City_name = input("Enter a city :")
print("=========Mobile Brands===============")
mobile_brands = []
mobile_brands.append(input("Enter a require 1st mobile brands :"))
mobile_brands.append(input("Enter a require 2nd mobile brands :"))
mobile_brands.append(input("Enter a require 3rd mobile brands :"))
mobile_brands.append(input("Enter a require 4rt mobile brands :"))
mobile_brands.append(input("Enter a require 5th mobile brands :"))
mobile_price=[]
mobile_price.append(float(input("Enter a price which you can pay:")))
mobile_price.append(float(input("Enter a price which you can pay:")))
mobile_price.append(float(input("Enter a price which you can pay:")))
mobile_price.append(float(input("Enter a price which you can pay:")))
mobile_price.append(float(input("Enter a price which you can pay:")))
print ("==========Customer Favourite Brands=============")
favourte_brands=("Samsung", "Apple", "Infinix", "Samsung", "Vivo", "Samsung")
print("Most demanded brand is : ",favourte_brands.count("sumsung"))
print("the index of apple :",favourte_brands.index("Apple"))
mobile_brands.append(input("Enter a new mobile brand name which is your favourit:"))
mobile_brands.insert(2,"realme")
mobile_brands.remove("sumsung")
mobile_brands.reverse()
mobile_brands.sort()
print("After changes in list",mobile_brands)
total_price=mobile_price[0]+mobile_price[1]+mobile_price[2]+mobile_price[3]+mobile_price[4]
print("Total price is :",total_price)
print("Averge price is :",total_price/5)
print("Lowest price is :",min(mobile_price))
print("Higest price is :",max(mobile_price))
print ("You will get a 10 percent discount",total_price/100*90)
if(total_price>=50000):
    print("================ VIP Customer - You get a free mobile cover!================")
elif(total_price>=30000):
    print("================ You get free earphones!================")
else:
    print("================ Thank you for visiting our store.================")