Customer_Name = input("Enter a name :")
PhoneNumber = int(input("Enter a Phone Number :"))
City = input("Enter a city :")
product_names=[]
product_names.append(input("Enter a 1st product :"))
product_names.append(input("Enter a 2nd product :"))
product_names.append(input("Enter a 3rd product :"))
product_names.append(input("Enter a 4rt product :"))
product_names.append(input("Enter a 5th product :"))
product_price=[]
product_price.append(float(input("Enter a 1st product price:")))
product_price.append(float(input("Enter a 2nd product price :")))
product_price.append(float(input("Enter a 3rd product price :")))
product_price.append(float(input("Enter a 4rt product price :")))
product_price.append(float(input("Enter a 5th product price :")))
#output function
print("=========================")
print("      SHOPPING BILL      ")
print("=========================")
print("customer name :",Customer_Name)
print ("Phone number :",PhoneNumber)
print("city :",City)
print("Product name :",product_names)
print("Product price :",product_price)
Total= product_price[0]+product_price[1]+product_price[2]+product_price[3]+product_price[4]
print("-------------------------")
print(" Total Bill:",Total)
print("Averge Price:",Total/2)
print("Highest Price:",max(product_price))
print("Lowest Price :",min(product_price))
print("-------------------------")
print("Thank you for shopping!")