numbers=set()
numbers.add(input("Enter a 1st number :"))
numbers.add(input("Enter a 2nd number :"))
numbers.add(input("Enter a 3rd number :"))
numbers.add(input("Enter a 4rt number :"))
numbers.add(input("Enter a 5th number :"))
numbers.add(input("Enter a 6   number :"))
numbers.add(input("Enter a 7   number :"))
numbers.add(input("Enter a 8   number :"))
numbers.add(input("Enter a 9   number :"))
numbers.add(input("Enter a 10  number :"))
print("All unquie number is : ",len(numbers))
